/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  IteneDashboard: () => import('#controllers/itene_dashboard_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
