/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class IteneConstructionRoomSchema extends BaseModel {
  static $columns = ['buildingId', 'constructionCode', 'constructionId', 'createdAt', 'floorNo', 'hasAdditionalFlag', 'hasMessage', 'hasOption', 'hasRemarks', 'hasReservation', 'id', 'iteneConstructionId', 'iteneCreatedAt', 'iteneRoomId', 'iteneUpdatedAt', 'lastSyncedAt', 'optionItems', 'optionPaid', 'raw', 'roomNo', 'spaceCode', 'spaceName', 'status', 'updatedAt'] as const
  $columns = IteneConstructionRoomSchema.$columns
  @column()
  declare buildingId: bigint | number | null
  @column()
  declare constructionCode: string | null
  @column()
  declare constructionId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare floorNo: number | null
  @column()
  declare hasAdditionalFlag: boolean
  @column()
  declare hasMessage: boolean
  @column()
  declare hasOption: boolean
  @column()
  declare hasRemarks: boolean
  @column()
  declare hasReservation: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iteneConstructionId: number
  @column.dateTime()
  declare iteneCreatedAt: DateTime | null
  @column()
  declare iteneRoomId: bigint | number
  @column.dateTime()
  declare iteneUpdatedAt: DateTime | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare optionItems: string | null
  @column()
  declare optionPaid: boolean
  @column()
  declare raw: any | null
  @column()
  declare roomNo: string | null
  @column()
  declare spaceCode: string | null
  @column()
  declare spaceName: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IteneConstructionSchema extends BaseModel {
  static $columns = ['breakEndTime', 'breakStartTime', 'buildingCompleteOnDate', 'buildingHousehold', 'buildingId', 'buildingName', 'code', 'createdAt', 'id', 'iteneCreatedAt', 'iteneId', 'iteneUpdatedAt', 'lastSyncedAt', 'messageToResident', 'name', 'raw', 'reservationAcceptancePeriodEndOn', 'reservationAcceptancePeriodStartOn', 'residentialPeriodEndOn', 'residentialPeriodStartOn', 'status', 'updatedAt', 'wholePeriodEndOn', 'wholePeriodStartOn', 'workEndTime', 'workStartTime'] as const
  $columns = IteneConstructionSchema.$columns
  @column()
  declare breakEndTime: string | null
  @column()
  declare breakStartTime: string | null
  @column.date()
  declare buildingCompleteOnDate: DateTime | null
  @column()
  declare buildingHousehold: number | null
  @column()
  declare buildingId: bigint | number | null
  @column()
  declare buildingName: string | null
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare iteneCreatedAt: DateTime | null
  @column()
  declare iteneId: bigint | number
  @column.dateTime()
  declare iteneUpdatedAt: DateTime | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare messageToResident: string | null
  @column()
  declare name: string | null
  @column()
  declare raw: any | null
  @column.date()
  declare reservationAcceptancePeriodEndOn: DateTime | null
  @column.date()
  declare reservationAcceptancePeriodStartOn: DateTime | null
  @column.date()
  declare residentialPeriodEndOn: DateTime | null
  @column.date()
  declare residentialPeriodStartOn: DateTime | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare wholePeriodEndOn: DateTime | null
  @column.date()
  declare wholePeriodStartOn: DateTime | null
  @column()
  declare workEndTime: string | null
  @column()
  declare workStartTime: string | null
}

export class IteneReservationSchema extends BaseModel {
  static $columns = ['additionalFlag', 'constructionId', 'constructionRoomId', 'createdAt', 'endAt', 'floorNo', 'id', 'iteneConstructionRoomId', 'iteneCreatedAt', 'iteneReservationId', 'iteneUpdatedAt', 'lastSyncedAt', 'lockRoomOwner', 'mainCharge', 'raw', 'reservationDate', 'roomNo', 'startAt', 'status', 'subCharge', 'updatedAt'] as const
  $columns = IteneReservationSchema.$columns
  @column()
  declare additionalFlag: boolean
  @column()
  declare constructionId: bigint | number | null
  @column()
  declare constructionRoomId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endAt: DateTime | null
  @column()
  declare floorNo: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iteneConstructionRoomId: number
  @column.dateTime()
  declare iteneCreatedAt: DateTime | null
  @column()
  declare iteneReservationId: bigint | number
  @column.dateTime()
  declare iteneUpdatedAt: DateTime | null
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare lockRoomOwner: boolean
  @column()
  declare mainCharge: string | null
  @column()
  declare raw: any | null
  @column.dateTime()
  declare reservationDate: DateTime | null
  @column()
  declare roomNo: string | null
  @column.dateTime()
  declare startAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare subCharge: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IteneRoomWorkSlotSchema extends BaseModel {
  static $columns = ['cancelLocked', 'createdAt', 'endTime', 'id', 'iteneConstructionRoomId', 'iteneReservationId', 'raw', 'reservationStatus', 'sequence', 'startTime', 'updatedAt', 'workDate', 'workType'] as const
  $columns = IteneRoomWorkSlotSchema.$columns
  @column()
  declare cancelLocked: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endTime: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iteneConstructionRoomId: number
  @column()
  declare iteneReservationId: bigint | number | null
  @column()
  declare raw: any | null
  @column()
  declare reservationStatus: string | null
  @column()
  declare sequence: number
  @column()
  declare startTime: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.date()
  declare workDate: DateTime | null
  @column()
  declare workType: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
