import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('itene_constructions', (table) => {
      table.increments('id').notNullable()
      table.bigInteger('itene_id').unsigned().notNullable().unique()
      table.string('code').nullable().index()
      table.string('name').nullable()
      table.string('building_name').nullable().index()
      table.bigInteger('building_id').unsigned().nullable().index()
      table.integer('building_household').nullable()
      table.date('building_complete_on_date').nullable()
      table.date('reservation_acceptance_period_start_on').nullable()
      table.date('reservation_acceptance_period_end_on').nullable()
      table.date('whole_period_start_on').nullable().index()
      table.date('whole_period_end_on').nullable().index()
      table.date('residential_period_start_on').nullable()
      table.date('residential_period_end_on').nullable()
      table.string('status').nullable().index()
      table.time('work_start_time').nullable()
      table.time('work_end_time').nullable()
      table.time('break_start_time').nullable()
      table.time('break_end_time').nullable()
      table.text('message_to_resident').nullable()
      table.timestamp('itene_created_at').nullable()
      table.timestamp('itene_updated_at').nullable()
      table.json('raw').nullable()
      table.timestamp('last_synced_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('itene_construction_rooms', (table) => {
      table.increments('id').notNullable()
      table
        .integer('itene_construction_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('itene_constructions')
        .onDelete('CASCADE')
      table.bigInteger('itene_room_id').unsigned().notNullable().unique()
      table.bigInteger('construction_id').unsigned().nullable().index()
      table.string('construction_code').nullable().index()
      table.bigInteger('building_id').unsigned().nullable().index()
      table.integer('floor_no').nullable().index()
      table.string('room_no').nullable().index()
      table.string('space_code').nullable().index()
      table.string('space_name').nullable()
      table.string('status').nullable().index()
      table.boolean('has_reservation').notNullable().defaultTo(false).index()
      table.boolean('has_message').notNullable().defaultTo(false)
      table.boolean('has_remarks').notNullable().defaultTo(false)
      table.boolean('has_additional_flag').notNullable().defaultTo(false)
      table.timestamp('itene_created_at').nullable()
      table.timestamp('itene_updated_at').nullable()
      table.json('raw').nullable()
      table.timestamp('last_synced_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['itene_construction_id', 'room_no'])
    })

    this.schema.createTable('itene_reservations', (table) => {
      table.increments('id').notNullable()
      table
        .integer('itene_construction_room_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('itene_construction_rooms')
        .onDelete('CASCADE')
      table.bigInteger('itene_reservation_id').unsigned().notNullable().unique()
      table.bigInteger('construction_id').unsigned().nullable().index()
      table.bigInteger('construction_room_id').unsigned().nullable().index()
      table.integer('floor_no').nullable().index()
      table.string('room_no').nullable().index()
      table.timestamp('start_at').nullable().index()
      table.timestamp('end_at').nullable()
      table.string('status').nullable().index()
      table.boolean('additional_flag').notNullable().defaultTo(false)
      table.boolean('lock_room_owner').notNullable().defaultTo(false)
      table.string('main_charge').nullable()
      table.string('sub_charge').nullable()
      table.timestamp('reservation_date').nullable()
      table.timestamp('itene_created_at').nullable()
      table.timestamp('itene_updated_at').nullable()
      table.json('raw').nullable()
      table.timestamp('last_synced_at').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
    })

    this.schema.createTable('itene_room_work_slots', (table) => {
      table.increments('id').notNullable()
      table
        .integer('itene_construction_room_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('itene_construction_rooms')
        .onDelete('CASCADE')
      table.bigInteger('itene_reservation_id').unsigned().nullable().index()
      table.string('work_type').notNullable().index()
      table.integer('sequence').notNullable()
      table.date('work_date').nullable().index()
      table.time('start_time').nullable()
      table.time('end_time').nullable()
      table.string('reservation_status').nullable().index()
      table.boolean('cancel_locked').nullable()
      table.json('raw').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()

      table.unique(['itene_construction_room_id', 'work_type', 'sequence'])
    })
  }

  async down() {
    this.schema.dropTable('itene_room_work_slots')
    this.schema.dropTable('itene_reservations')
    this.schema.dropTable('itene_construction_rooms')
    this.schema.dropTable('itene_constructions')
  }
}
